const main = async () => {
  console.log('Hello world!');
};

main().catch(err => console.error(err));
